curo/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path

from . import views

app_name = "tienda"

urlpatterns = [
    path("", views.index, name="index"),
    path("collage/", views.collage, name="collage")
]

tienda/models.py
from django.db import models

# Create your models here.

class Productos(models.Model):
    COLECCIONES = (
        (1, 'Curandera'),
    ) 
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    coleccion = models.IntegerField(choices=COLECCIONES, default=1)
    foto = models.ImageField(null=True, blank=True, default='fotos_productos/default.png', upload_to='fotos_productos')

class Usuarios(models.Model):
    ROLES = (
        (1, 'Administrador'),
        (2, 'Usuario'),
    )
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, unique=True)
    password = models.CharField(max_length=16)
    rol = models.IntegerField(choices=ROLES, default=2)

tienda/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from django.db.models import Q

from django.contrib import messages

from .models import *


# Create your views here.

def index(request):
    return render(request, "index.html")


def collage(request):
    return render(request, "collage.html")

tienda/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CURO - {% block titul %} {% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'tienda/css/styles.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg" style="background-color: #D6CAA1;">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto align-items-center">
                    <a class="navbar-brand" href="{% url 'tienda:index' %}"><img src="{% static 'tienda/img/logo_principal.png' %}" alt=""></a>
                </ul>
            </div>
        </div>
    </nav>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible"
        role="alert">
        <div>{{ message }}</div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}

    {% block contenedor %}

    {% endblock %}

    <footer class="d-flex justify-content-between align-items-center" style="background-color: #D6CAA1;">
        <div class="col-md-4 d-flex align-items-center pt-2 pb-2">
            <a href="{% url 'tienda:index' %}" class="mb-3 me-2 mb-md-0 text-muted">
                <img src="{% static 'tienda/img/logo_principal.png' %}" alt="">
            </a>
            <span class="mb-3 mb-md-0 text-muted">© 2023 Company, Inc</span>
        </div>
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3">
                <a href="https://www.instagram.com/curo_bynatalia/" class="text-muted" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="34" fill="currentColor"
                        class="bi bi-instagram" viewBox="0 0 16 16">
                        <path
                            d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
                    </svg>
                </a>
            </li>
            <li class="ms-3">
                <a href="mailto:curobynataliar@gmail.com" class="text-muted">
                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="34" fill="currentColor"
                        class="bi bi-envelope" viewBox="0 0 16 16">
                        <path
                            d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
                    </svg>
                </a>
            </li>
        </ul>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'tienda/js/scripts.js' %}"></script>
</body>

</html>

tienda/templates/collage.html
{% extends 'base.html' %}

{% load static %}

{% block titul %} Collage {% endblock %}

{% block contenedor %}
    <style>
        .collage{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
        }
        .foto{
            width: 100%;
            height: auto;
            transition: transform 0.3s;
        }
        .foto:hover{
            transform: scale(1.2);
        }
    </style>
    <main>
        <section>
            <div class="collage">
                <img src="{% static 'tienda/img/1.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/2.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/3.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/4.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/5.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/6.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/7.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/8.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/9.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/10.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/11.jpg' %}" alt="" class="foto">
                <img src="{% static 'tienda/img/12.jpg' %}" alt="" class="foto">
            </div>
        </section>
    </main>

{% endblock %}

tienda/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block titul %} Inicio {% endblock %}

{% block contenedor %}
    <style>
        .carousel-item{
            position: relative;
        }
        .carousel-item .btn{
            position: absolute;
            bottom: 240px;
            left: 200px;
            z-index: 1;
            background-color: #D6CAA1;
        }
    </style>
    <main>
        <section>
            <div id="carouselExampleFade" class="carousel slide carousel-fade">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="{% static 'tienda/img/home.png' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'tienda/img/home2T.jpg' %}" class="d-block w-100" alt="...">
                    <a href="{% url 'tienda:collage' %}" class="btn">Descubre Mas</a>
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
        </section>
        <section class="mt-4">
            <div class="d-flex justify-content-evenly">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'tienda/img/vestidoB.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <p class="text-center">Renacer</p>
                    </div>
                </div>
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'tienda/img/vestido.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <p class="text-center">Conectar</p>
                    </div>
                </div>
            </div>
        </section>
        <section class="mt-4">
            <h3 class="text-center">¿Quiénes Somos?</h3>
                <div class="container text-center mt-3">
                  <div class="row align-items-start">
                    <div class="col">
                        <h4>Mision</h4>
                        <p>Nuestra misión es empoderar honrar y celebrar a las mujeres; somo una empresa creada por mujeres y hecha a mano por mujeres, creemos en el rol activo que cumplimos positivamente en la sociedad.</p>
                        <img src="{% static 'tienda/img/mision.png' %}" style="width: 100%">
                    </div>
                    <div class="col">
                        <h4>Vision</h4>
                        <p class="mb-5">En el 2028 nos visualizamos como una empresa que ha devuelto y fortalecido la esencia de ser mujer, donde contamos la historia de las mujeres que hemos empoderado y sanado estas heridas.</p>
                        <img src="{% static 'tienda/img/vision.png' %}" style="width: 78%">
                    </div>
                  </div>
                </div>
        </section>
    </main>
    
{% endblock %}